#!/bin/bash -e

commitishA=$1
commitishB=$2

tmux new \
   -s git-tlog \
   "git log $commitishA..$commitishB ; $SHELL" \;\
   select-layout tiled \;\
   split-window -h \
   "git log $commitishB..$commitishA ; $SHELL" \;\
   select-pane -t 0 # Focus back on the left pane.


